tweaks, fixes, and updates for aarch64 architecture (aka arm64)

diff --git a/jni/src/configure b/jni/src/configure
--- a/jni/src/configure
+++ b/jni/src/configure
@@ -42,12 +42,21 @@ elif [ "$ARCH" = "amd64" ] || [ "$ARCH" = "x86_64" ] ; then
     MBITS=64
 elif [[ "$ARCH" == armv7* ]] ; then
     ARCH="arm"
-    ARMARCH="armv7-a"
     MBITS=32
+    ARMFLAGS="-marm -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard"
 elif [ "$ARCH" = "aarch64" ] ; then
-    ARCH="arm"
-    ARMARCH="armv8-a"
+    ARCH="aarch64"
     MBITS=64
+
+    gcc cpuid_arm64.c -o cpuid_arm64 >/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo 'failed to compile cpuid_arm64, aborting' && exit 1
+    fi
+    if [[ $(./cpuid_arm64) == "CORTEXA57" ]]; then
+        ARMFLAGS="-march=armv8-a+crc+crypto+fp+simd -mtune=cortex-a57"
+    else
+        ARMFLAGS="-march=armv8-a"
+    fi
 else
     echo "ARCH not supported"
     exit 1
@@ -119,19 +128,17 @@ if [ "$OS" = "apple" ] ; then
     INSTALL_DIR="${BIDMAT_ROOT}/src/main/resources/lib"
     CUDA_LIBS="-L${CUDA_HOME}/lib -L${LIBDIR} -lcudart -lcublas"
 elif [ "$OS" = "linux" ] ; then
-    if [ "$ARCH" = "arm" ] ; then
+    if [ "$ARCH" = "arm" ] || [[ "$ARCH" = "aarch64" ]] ; then
 	RANDSRC="RAND"
 	if [ "$QSML_ROOT" != "" ]; then
 	    BLAS_INCLUDE="-I$QSML_ROOT/include"
 	    BLAS_LIB="-L$QSML_ROOT/lib -lQSML -lsymphony-cpu"
+	elif [ "$OPENBLAS_ROOT" != "" ]; then
+	    BLAS_INCLUDE="-I$OPENBLAS_ROOT/include"
+	    BLAS_LIB="-L$OPENBLAS_ROOT/lib -lopenblas"
 	else
-	    if [ "$OPENBLAS_ROOT" != "" ]; then
-		BLAS_INCLUDE="-I$OPENBLAS_ROOT/include"
-		BLAS_LIB="-L$OPENBLAS_ROOT/lib -lopenblas"
-	    else
-		BLAS_INCLUDE="-I/usr/local/include"
-		BLAS_LIB="-L/usr/local/lib -lopenblas"
-	    fi
+	    BLAS_INCLUDE="-I/usr/local/include"
+	    BLAS_LIB="-L/usr/local/lib -lopenblas"
 	fi
 	if [ "$JAVA_HOME" = "" ]; then
 	    JAVA_HOME="/usr/java/default"
@@ -142,14 +149,17 @@ elif [ "$OS" = "linux" ] ; then
 	CC="gcc"
 	GCC="g++"
 	NVCC="nvcc" 
-	NVCCFLAGS="-c -use_fast_math -I$BIDMAT_ROOT/jni/include \
-          --maxrregcount=31 \
-          -gencode arch=compute_32,code=sm_32 \
-          --machine ${MBITS}  -Xcompiler \"-fPIC -c -O2 -g -march=${ARMARCH} -DNDEBUG\""
+	if [ "$ARCH" = "arm" ] ; then
+            NVARCH="-gencode arch=compute_32,code=sm_32"
+	else
+            NVARCH="-gencode arch=compute_53,code=sm_53 \
+                    -gencode arch=compute_53,code=compute_53"
+	fi
+	NVCCFLAGS="-c -use_fast_math -I$BIDMAT_ROOT/jni/include --maxrregcount=31 ${NVARCH} --machine ${MBITS} -Xcompiler \"-fPIC -c -O2 -g ${ARMFLAGS} -DNDEBUG\""
 	OBJ="o"
 	OUTFLG="-o "
-	CPPFLAGS="-fPIC -std=c++11 -marm -mfpu=vfpv3 -mfloat-abi=hard -march=${ARMARCH} -c -O2 -DNDEBUG -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$BIDMAT_ROOT/jni/include -I$CUDA_HOME/include ${BLAS_INCLUDE}"
-	CFLAGS="-fPIC -fopenmp -marm -mfpu=vfpv3 -mfloat-abi=hard -march=${ARMARCH} -c -O2 -DNDEBUG -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$BIDMAT_ROOT/jni/include ${BLAS_INCLUDE}"
+	CPPFLAGS="-fPIC -std=c++11 ${ARMFLAGS} -c -O2 -DNDEBUG -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$BIDMAT_ROOT/jni/include -I$CUDA_HOME/include ${BLAS_INCLUDE}"
+	CFLAGS="-fPIC -fopenmp ${ARMFLAGS} -c -O2 -DNDEBUG -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$BIDMAT_ROOT/jni/include ${BLAS_INCLUDE}"
 	LB="ar rc"    
 	GLD="g++ -shared"
 	LD="gcc -shared -z noexecstack"
